import {date} from 'quasar';
import {lodash} from '@iy4u/common-client-lib';

const {$lget} = lodash;

export const essentialFieldsConfig = [
  {
    name: 'createdBy',
    label: 'Created By',
    align: 'left',
    field: row => $lget(row, '_fastjoin.createdBy.user.email', 'N/A'),
    format: val => `${val}`,
    sortable: true,
    hidden: true,
  },
  {
    name: 'updatedBy',
    label: 'Updated By',
    align: 'left',
    field: row => $lget(row, '_fastjoin.updatedBy.user.email', 'N/A'),
    format: val => `${val}`,
    sortable: true,
    hidden: true,
  },
  {
    name: 'createdAt',
    label: 'Created At',
    align: 'left',
    field: row => date.formatDate(row.createdAt, 'DD-MM-YYYY hh:mm A'),
    format: val => `${val}`,
    sortable: true,
    hidden: true,
  },
  {
    name: 'updatedAt',
    label: 'Updated At',
    align: 'left',
    field: row => date.formatDate(row.updatedAt, 'DD-MM-YYYY hh:mm A'),
    format: val => `${val}`,
    sortable: true,
    hidden: true,
  },
  {
    name: 'updatedByHistory',
    label: 'Update History',
    align: 'left',
    field: row => $lget(row, 'updatedByHistory', []),
    format: val => val,
    sortable: true,
    isExpansion: true,
    hidden: true,
  },
  {
    name: 'externalCreatedBySource',
    label: 'External Created By',
    align: 'left',
    field: row => $lget(row, 'external.createdBySource', []),
    format: val => `${val}`,
    sortable: true,
    hidden: true,
    // isExpansion: true,
  },
  {
    name: 'externalUpdatedBySource',
    label: 'External Updated By',
    align: 'left',
    field: row => $lget(row, 'external.updatedBySource', []),
    format: val => `${val}`,
    sortable: true,
    hidden: true,
    // isExpansion: true,
  },
  {
    name: 'externalUpdatedBySourceHistory',
    label: 'External Updated By History',
    align: 'left',
    field: row => $lget(row, 'external.updatedBySourceHistory', []),
    format: val => `${val}`,
    sortable: true,
    hidden: true,
    // isExpansion: true,
  },
  // {
  //   name: 'deleted',
  //   label: 'Deleted',
  //   align: 'left',
  //   field: row => $lget(row, 'deleted'),
  //   format: val => val,
  //   sortable: true,
  //   hidden: true,
  // },
  // {
  //   name: 'deletedAt',
  //   label: 'Deleted At',
  //   align: 'left',
  //   field: row => row.deletedAt ? date.formatDate(row.deletedAt, 'DD-MM-YYYY hh:mm A') : 'N/A',
  //   format: val => `${val}`,
  //   sortable: true,
  //   hidden: true,
  // },
];
